[package]
name = "renderer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
geometry_core = { path = "../geometry_core" }
layout_model = { path = "../layout_model" }
web-time.workspace = true
wgpu.workspace = true
