#![allow(unused_imports)]
use super::*;

pub struct GlassworksApp {
    pub(crate) workspace: WorkspaceDataset,
    pub(crate) active_view: StartupView,
    pub(crate) active_menu: Option<AppMenu>,
    pub(crate) active_view_group: Option<ModuleGroup>,
    pub(crate) active_tool: ToolMode,
    pub(crate) layout_zoom: f32,
    pub(crate) layout_pan: [f32; 2],
    pub(crate) layout_pointer: Option<UiPoint>,
    pub(crate) layout_canvas_size: Option<UiSize>,
    pub(crate) layout_drag: Option<LayoutCanvasDrag>,
    pub(crate) layout_3d_drag: Option<UiPoint>,
    pub(crate) camera_3d: Camera3d,
    pub(crate) flycam_captured: bool,
    pub(crate) viewport_fullscreen: bool,
    pub(crate) drawing_start: Option<Point>,
    pub(crate) drawing_points: Vec<Point>,
    pub(crate) measure_start: Option<Point>,
    pub(crate) route_points: Vec<Point>,
    pub(crate) layout_frame_ms: StdCell<Option<f64>>,
    pub(crate) layout_frame_ema_ms: StdCell<Option<f64>>,
    pub(crate) layout_frame_last_at: StdCell<Option<std::time::Instant>>,
    pub(crate) layout_revision: u64,
    pub(crate) layout_view_revision: u64,
    pub(crate) layout_view_top_cell: CellId,
    pub(crate) layout_hierarchy_depth: LayoutHierarchyDepth,
    pub(crate) layout_hierarchy_min_depth: u8,
    pub(crate) layout_previous_view: Option<LayoutViewState>,
    pub(crate) layout_view_bookmarks: BTreeMap<u8, LayoutViewState>,
    pub(crate) layout_view_bookmark_names: BTreeMap<u8, String>,
    pub(crate) layout_layer_sets: BTreeMap<u8, LayoutLayerSetState>,
    pub(crate) layout_layer_set_names: BTreeMap<u8, String>,
    pub(crate) layout_layer_group_filter: LayoutLayerGroupFilter,
    pub(crate) layout_layer_usage_filter: LayoutLayerUsageFilter,
    pub(crate) layout_layer_depth_overrides: BTreeMap<LayerId, LayoutHierarchyDepth>,
    pub(crate) layout_measurement_mode: MeasurementMode,
    pub(crate) layout_measurement_filter: LayoutMeasurementFilter,
    pub(crate) layout_active_technology_index: usize,
    pub(crate) layout_active_technology: TechnologyFile,
    pub(crate) layout_disabled_connectivity_links: BTreeSet<usize>,
    pub(crate) layout_library_via_array_presets: BTreeMap<u8, LayoutViaArrayLibraryPreset>,
    pub(crate) layout_library_via_array_columns: u8,
    pub(crate) layout_library_via_array_rows: u8,
    pub(crate) layout_library_via_array_size_grids: Coord,
    pub(crate) layout_library_via_array_pitch_grids: Coord,
    pub(crate) layout_import_offset: Vector,
    pub(crate) layout_import_layer_policy: LayoutImportLayerPolicy,
    pub(crate) layout_import_layer_id_offset: i32,
    pub(crate) layout_tree_collapsed_cells: BTreeSet<CellId>,
    pub(crate) layout_hidden_cells: BTreeSet<CellId>,
    pub(crate) layout_index_cache: RefCell<Option<LayoutIndexCacheValue>>,
    pub(crate) connectivity_report_cache: RefCell<Option<ConnectivityReportCacheValue>>,
    pub(crate) layout_spice_comparison: Option<SpiceConnectivityComparisonReport>,
    pub(crate) drc_report_cache: RefCell<Option<DrcReportCacheEntry>>,
    pub(crate) layout_drc_report_history: Vec<DrcReportHistoryEntry>,
    pub(crate) layout_selected_drc_report_id: Option<u64>,
    pub(crate) layout_next_drc_report_id: u64,
    pub(crate) layout_custom_drc_deck: Option<RuleDeck>,
    pub(crate) layout_custom_drc_deck_label: Option<String>,
    pub(crate) nav_rail_views: BTreeSet<StartupView>,
    pub(crate) active_layer: LayerId,
    pub(crate) selected_layout_shape: Option<ShapeId>,
    pub(crate) selected_layout_occurrence: Option<ShapeOccurrenceId>,
    pub(crate) layout_shape_browser_filter: LayoutShapeBrowserFilter,
    pub(crate) layout_shape_browser_sort: LayoutShapeBrowserSort,
    pub(crate) layout_cell_browser_filter: LayoutCellBrowserFilter,
    pub(crate) layout_cell_browser_sort: LayoutCellBrowserSort,
    pub(crate) layout_net_browser_filter: LayoutNetBrowserFilter,
    pub(crate) layout_net_browser_sort: LayoutNetBrowserSort,
    pub(crate) layout_trace_highlight_mode: LayoutTraceHighlightMode,
    pub(crate) layout_instance_browser_scope: LayoutInstanceBrowserScope,
    pub(crate) layout_instance_browser_filter: LayoutInstanceBrowserFilter,
    pub(crate) layout_instance_browser_sort: LayoutInstanceBrowserSort,
    pub(crate) layout_browser_search: String,
    pub(crate) layout_browser_search_active: bool,
    pub(crate) layout_browser_replace: String,
    pub(crate) layout_browser_replace_active: bool,
    pub(crate) layout_browser_replace_scope: LayoutBrowserReplaceScope,
    pub(crate) layout_browser_columns: LayoutBrowserColumnSet,
    pub(crate) layout_drc_marker_filter: LayoutDrcMarkerFilter,
    pub(crate) layout_drc_marker_sort: LayoutDrcMarkerSort,
    pub(crate) layout_drc_marker_category_filter: Option<LayoutDrcMarkerCategory>,
    pub(crate) layout_selected_drc_marker_key: Option<String>,
    pub(crate) layout_trace_history: Vec<usize>,
    pub(crate) layout_clipboard_shapes: Vec<Shape>,
    pub(crate) layout_undo: Vec<UndoEntry>,
    pub(crate) layout_redo: Vec<UndoEntry>,
    pub(crate) workflow_focus_lot: Option<String>,
    pub(crate) selected_equipment_tool: Option<EquipmentToolId>,
    pub(crate) equipment_recipe_drafts: BTreeMap<EquipmentToolId, EquipmentRecipeId>,
    pub(crate) selected_maintenance_tool: Option<EquipmentToolId>,
    pub(crate) maintenance_work_filter: MaintenanceWorkFilter,
    pub(crate) maintenance_history_filter: MaintenanceHistoryFilter,
    pub(crate) selected_environment_sensor: Option<String>,
    pub(crate) selected_inventory_lot: Option<MaterialLotId>,
    pub(crate) inventory_filter: InventoryQuickFilter,
    pub(crate) mask_source_lot: Option<LotId>,
    pub(crate) mask_issue_severity_filter: MaskIssueSeverityFilter,
    pub(crate) mask_issue_grouping: MaskIssueGrouping,
    pub(crate) mask_issue_page: usize,
    pub(crate) layout_diff_baseline: LayoutDiffSource,
    pub(crate) layout_diff_candidate: LayoutDiffSource,
    pub(crate) layout_diff_changed_only: bool,
    pub(crate) layout_diff_change_filter: LayoutChangeFilter,
    pub(crate) layout_diff_change_page: usize,
    pub(crate) layout_diff_page_size: usize,
    pub(crate) layout_diff_review_state: LayoutReviewDisposition,
    pub(crate) selected_trace_lot: Option<LotId>,
    pub(crate) selected_trace_wafer: Option<WaferId>,
    pub(crate) selected_trace_detail: Option<TraceSelection>,
    pub(crate) trace_impact_mode: TraceImpactMode,
    pub(crate) trace_related_only: bool,
    pub(crate) selected_notebook_entry: Option<NotebookEntryId>,
    pub(crate) notebook_tag_filter: Option<String>,
    pub(crate) notebook_link_kind_filter: Option<NotebookLinkKind>,
    pub(crate) notebook_preview_mode: bool,
    pub(crate) notebook_followups_only: bool,
    pub(crate) scheduler_policy: DispatchPolicy,
    pub(crate) selected_scheduler_tool: Option<SchedulerToolId>,
    pub(crate) scheduler_min_priority: u8,
    pub(crate) scheduler_conflicts_only: bool,
    pub(crate) scheduler_focus_selected_tool: bool,
    pub(crate) selected_safety_tool: Option<String>,
    pub(crate) acknowledged_conditions: BTreeSet<String>,
    pub(crate) acknowledged_lockouts: BTreeSet<String>,
    pub(crate) acknowledged_incidents: BTreeSet<String>,
    pub(crate) selected_process_node: Option<ProcessFlowNodeId>,
    pub(crate) process_flow_filter: ProcessFlowNodeFilter,
    pub(crate) process_flow_errors_only: bool,
    pub(crate) process_control_loop_filter: ControlLoopFilter,
    pub(crate) selected_control_loop: Option<ControlLoopId>,
    pub(crate) selected_control_action: Option<ControlActionId>,
    pub(crate) selected_spc_chart: Option<String>,
    pub(crate) selected_fdc_trace: Option<String>,
    pub(crate) spc_severity_filter: SpcSeverityFilter,
    pub(crate) spc_source_filter: SpcSourceFilter,
    pub(crate) spc_context_filter: String,
    pub(crate) cross_section_step: usize,
    pub(crate) selected_cross_section_material: Option<MaterialId>,
    pub(crate) cross_section_show_mask: bool,
    pub(crate) cross_section_show_dimensions: bool,
    pub(crate) cross_section_show_risks: bool,
    pub(crate) metrology_map_mode: MetrologyMapMode,
    pub(crate) metrology_kind: MeasurementKind,
    pub(crate) metrology_failed_only: bool,
    pub(crate) selected_die: Option<DieCoord>,
    pub(crate) yield_map_filter: YieldMapFilter,
    pub(crate) show_only_attention_wafers: bool,
    pub(crate) show_only_excursions: bool,
    pub(crate) selected_yield_lot: Option<String>,
    pub(crate) selected_yield_wafer: Option<String>,
    pub(crate) selected_experiment_run: Option<ExperimentRunId>,
    pub(crate) selected_experiment_response: Option<ResponseSpecId>,
    pub(crate) experiment_capture_value: f64,
    pub(crate) experiment_run_filter: ExperimentRunFilter,
    pub(crate) experiment_lot_filter: Option<String>,
    pub(crate) experiment_show_missing_only: bool,
    pub(crate) status_message: String,
    pub(crate) dark_theme: bool,
    pub(crate) theme_preference: options::ThemePreference,
    pub(crate) show_command_palette: bool,
    pub(crate) show_sidebar_modules: bool,
    pub(crate) show_options_panel: bool,
    pub(crate) show_diagnostics_panel: bool,
    pub(crate) collapsed_detail_sections: BTreeSet<String>,
    pub(crate) unit_display: UnitDisplay,
    pub(crate) snap_enabled: bool,
    pub(crate) show_grid: bool,
    pub(crate) show_3d_grid: bool,
    pub(crate) show_origin_marker: bool,
    pub(crate) show_drc_overlay: bool,
    pub(crate) show_reference_images: bool,
    pub(crate) show_inspector: bool,
    pub(crate) show_layers: bool,
    pub(crate) app_options: AppOptions,
    pub(crate) options_file_path: Option<String>,
    pub(crate) layout_modifiers: operad::KeyModifiers,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum LayoutCanvasDrag {
    MoveShape {
        shape_id: ShapeId,
        start_world: Point,
        last_world: Point,
        copy_on_drag: bool,
        added_shape: Option<Shape>,
    },
    MoveInstance {
        parent: CellId,
        instance_id: InstanceId,
        start_world: Point,
        last_world: Point,
        copy_on_drag: bool,
        added_instance: Option<CellInstance>,
    },
    MoveVertex {
        shape_id: ShapeId,
        vertex: usize,
        start_world: Point,
        original_position: Point,
        original_shape: Shape,
    },
    MoveEdge {
        shape_id: ShapeId,
        edge: usize,
        last_world: Point,
        original_shape: Shape,
    },
    Rect {
        start: Point,
    },
}

#[derive(Clone, Debug)]
pub(crate) struct UndoEntry {
    pub(crate) undo: Operation,
    pub(crate) redo: Operation,
}
