[package]
name = "wasm_app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glassworks_studio = { package = "native_app", path = "../native_app", default-features = false, features = ["native"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
glassworks_studio = { package = "native_app", path = "../native_app", default-features = false, features = ["web"] }
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Document", "Element", "HtmlCanvasElement", "Location", "Window"] }
